version: '3.7'

services:
  validator1:
    image: hyperledger/besu:latest
    container_name: validator1
    network_mode: host
    volumes:
      - ./validator1:/data
    command: >
      --genesis-file=/data/genesis.json
      --data-path=/data
      --rpc-http-enabled
      --rpc-http-api=ETH,NET,QBFT
      --host-whitelist="*"
      --rpc-http-cors-origins="all"
      --rpc-http-port=8545
      --p2p-port=30303

  validator2:
    image: hyperledger/besu:latest
    container_name: validator2
    network_mode: host
    volumes:
      - ./validator2:/data
    command: >
      --genesis-file=/data/genesis.json
      --data-path=/data
      --rpc-http-enabled
      --rpc-http-api=ETH,NET,QBFT
      --host-whitelist="*"
      --rpc-http-cors-origins="all"
      --rpc-http-port=8546
      --p2p-port=30304
      --bootnodes=enode://8bfa1ffcfe7be08235a4c0cffc2e5cf79a9f93dea2dd41e5e036e457fa7b72f58a83254cb3dd461396244c1f5e67b355e91245f3f3893e809211abd28a7ae3aa@127.0.0.1:30303
  

  validator3:
    image: hyperledger/besu:latest
    container_name: validator3
    network_mode: host
    volumes:
      - ./validator3:/data
    command: >
      --genesis-file=/data/genesis.json
      --data-path=/data
      --rpc-http-enabled
      --rpc-http-api=ETH,NET,QBFT
      --host-whitelist="*"
      --rpc-http-cors-origins="all"
      --rpc-http-port=8547
      --p2p-port=30305
      --bootnodes=enode://8bfa1ffcfe7be08235a4c0cffc2e5cf79a9f93dea2dd41e5e036e457fa7b72f58a83254cb3dd461396244c1f5e67b355e91245f3f3893e809211abd28a7ae3aa@127.0.0.1:30303
 

  validator4:
    image: hyperledger/besu:latest
    container_name: validator4
    network_mode: host
    volumes:
      - ./validator4:/data
    command: >
      --genesis-file=/data/genesis.json
      --data-path=/data
      --rpc-http-enabled
      --rpc-http-api=ETH,NET,QBFT
      --host-whitelist="*"
      --rpc-http-cors-origins="all"
      --rpc-http-port=8548
      --p2p-port=30306
      --bootnodes=enode://8bfa1ffcfe7be08235a4c0cffc2e5cf79a9f93dea2dd41e5e036e457fa7b72f58a83254cb3dd461396244c1f5e67b355e91245f3f3893e809211abd28a7ae3aa@127.0.0.1:30303

volumes:
  pgdata:
